#!/bin/bash
#
# BITRUN One-Click Installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/YOUR_ORG/BitRun/main/install.sh | bash
#
# This script:
#   1. Checks for Docker and Docker Compose
#   2. Downloads the latest docker-compose.prod.yml
#   3. Starts all services (Backend, Frontend, PostgreSQL, Redis)
#   4. Runs database migrations
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

echo -e "${CYAN}"
echo "  ╔═══════════════════════════════════╗"
echo "  ║   BITRUN — One-Click Installer    ║"
echo "  ║   AI-Powered Trading Platform     ║"
echo "  ╚═══════════════════════════════════╝"
echo -e "${NC}"

# ==================== Check Docker ====================

if ! command -v docker &> /dev/null; then
    log_error "Docker is not installed."
    echo ""
    echo "  Install Docker:"
    echo "    Linux:  curl -fsSL https://get.docker.com | sh"
    echo "    macOS:  https://www.docker.com/products/docker-desktop"
    echo ""
    exit 1
fi

if ! docker info &> /dev/null 2>&1; then
    log_error "Docker daemon is not running. Please start Docker and try again."
    exit 1
fi

# Determine Docker Compose command
if docker compose version &> /dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose &> /dev/null; then
    COMPOSE="docker-compose"
else
    log_error "Docker Compose not found. Install Docker Desktop or docker-compose."
    exit 1
fi

log_success "Docker: $(docker --version | head -1)"
log_success "Compose: $($COMPOSE version 2>/dev/null | head -1)"

# ==================== Setup Directory ====================

INSTALL_DIR="${BITRUN_DIR:-$HOME/bitrun}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

log_info "Install directory: $INSTALL_DIR"

# ==================== Download Compose File ====================

COMPOSE_FILE="docker-compose.prod.yml"
REPO_URL="https://raw.githubusercontent.com/YOUR_ORG/BitRun/main"

if [ -f "$COMPOSE_FILE" ]; then
    log_info "Updating $COMPOSE_FILE..."
else
    log_info "Downloading $COMPOSE_FILE..."
fi

# If we can't download (offline / private repo), check if file exists
if command -v curl &> /dev/null; then
    curl -fsSL "$REPO_URL/$COMPOSE_FILE" -o "$COMPOSE_FILE" 2>/dev/null || true
fi

if [ ! -f "$COMPOSE_FILE" ]; then
    log_warn "Could not download compose file. Using local copy if available."
    if [ ! -f "$COMPOSE_FILE" ]; then
        log_error "No docker-compose file found. Please ensure $COMPOSE_FILE exists in $INSTALL_DIR"
        exit 1
    fi
fi

# ==================== Generate Secrets ====================

ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    log_info "Generating secrets..."

    # Generate secure random keys
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || echo "change-me-$(date +%s)")
    ENCRYPTION_KEY=$(openssl rand -base64 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || echo "change-me-$(date +%s)")

    cat > "$ENV_FILE" << EOF
# BITRUN Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

ENVIRONMENT=production
JWT_SECRET=$JWT_SECRET
DATA_ENCRYPTION_KEY=$ENCRYPTION_KEY

# Add your AI provider keys in the web interface (Models / Providers)
# No environment variables needed for AI - configure via UI
EOF

    log_success "Secrets generated and saved to $ENV_FILE"
else
    log_info "Using existing $ENV_FILE"
fi

# ==================== Pull & Start ====================

log_info "Pulling latest images..."
$COMPOSE -f "$COMPOSE_FILE" pull 2>/dev/null || true

log_info "Starting services..."
$COMPOSE -f "$COMPOSE_FILE" up -d

# ==================== Wait & Migrate ====================

log_info "Waiting for services to initialize (15s)..."
sleep 15

log_info "Running database migrations..."
$COMPOSE -f "$COMPOSE_FILE" exec -T backend alembic upgrade head 2>/dev/null || log_warn "Migration skipped (may already be up to date)"

# ==================== Done ====================

echo ""
echo -e "${GREEN}══════════════════════════════════════════${NC}"
echo -e "${GREEN}  BITRUN is running!${NC}"
echo -e "${GREEN}══════════════════════════════════════════${NC}"
echo ""
echo "  Open in browser:  http://localhost:3000"
echo "  API docs:         http://localhost:8000/docs"
echo "  Health check:     http://localhost:8000/health"
echo ""
echo "  Next steps:"
echo "    1. Register an account at http://localhost:3000"
echo "    2. Add AI provider keys in Model Management"
echo "    3. Connect your exchange account"
echo "    4. Create your first AI trading agent!"
echo ""
echo "  Manage:"
echo "    View logs:   $COMPOSE -f $COMPOSE_FILE logs -f"
echo "    Stop:        $COMPOSE -f $COMPOSE_FILE down"
echo "    Update:      Re-run this installer"
echo ""
